
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.54
distribution_type: module
version: 1.11111
name: Acme
author: "Ingy d\xC3\xB6t Net <ingy@cpan.org>"
license: perl
requires: 
  perl: 5.6.1
  Spiffy: 0.14
abstract: The Base of Perfection
